In [1]:
import numpy as np

arr=np.array(42)
print(arr)

42


In [2]:
arr.ndim

0

In [3]:
import numpy as np

my_list=[10,20,30,40,50]
print(my_list)

[10, 20, 30, 40, 50]


In [5]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
arr.ndim

1

In [7]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
arr.ndim

2

In [9]:
arr.size

6

In [10]:
arr.shape

(2, 3)

In [13]:
import numpy as np

my_list=[10,20,30,40,50]
arr=np.array(my_list)
print(arr)

[10 20 30 40 50]


In [17]:
import numpy as np

arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [18]:
arr.ndim

3

In [19]:
arr.shape

(2, 2, 3)

In [20]:
arr.size

12

In [1]:
import numpy as np

In [4]:
array_of_floats=np.arange(0,2,0.3)
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [5]:
import numpy as np

In [8]:
array_2d=np.array([[1,2,3],[4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
array_2d.shape

(2, 3)

In [11]:
import numpy as np

In [13]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [27]:
import numpy as np

array_2d=np.array([[1,2,3],[4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
array_2d.shape

(2, 3)

In [14]:
import numpy as np

In [15]:
array_nd=np.arange(6).reshape(3,2)

array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
array_nd.shape

(3, 2)

In [17]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [19]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])