In [1]:
import numpy as np

arr=np.array(42)
print(arr)

42


In [2]:
arr.ndim

0

In [3]:
import numpy as np

my_list=[10,20,30,40,50]
print(my_list)

[10, 20, 30, 40, 50]


In [5]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
arr.ndim

1

In [7]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
arr.ndim

2

In [9]:
arr.size

6

In [10]:
arr.shape

(2, 3)

In [13]:
import numpy as np

my_list=[10,20,30,40,50]
arr=np.array(my_list)
print(arr)

[10 20 30 40 50]


In [17]:
import numpy as np

arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [18]:
arr.ndim

3

In [19]:
arr.shape

(2, 2, 3)

In [20]:
arr.size

12

In [30]:
import numpy as np

array_of_floats=np.array(0,2,0.3)
array_of_floats

ValueError: only 2 non-keyword arguments accepted

In [27]:
import numpy as np

array_2d=np.array([[1,2,3],[4,5,6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
array_2d.shape

(2, 3)

In [37]:
import numpy as np

arr=np.arrange(6)
arr

AttributeError: module 'numpy' has no attribute 'arrange'

In [38]:
array_nd=np.arrange(6).reshape(3,2)

array_nd

AttributeError: module 'numpy' has no attribute 'arrange'