In [ ]:
#statistical functions of numpy:

In [1]:
import numpy as np

In [2]:
test_score=np.array([32.32,56.98,21.52,44.32,55.55,70.50])
print("mean test scores of the students:")
print(np.mean(test_score))

mean test scores of the students:
46.865


In [7]:
a=np.arange(11)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [8]:
for i in a:
    print(i**1/2)

0.0
0.5
2.0
4.5
8.0
12.5
18.0
24.5
32.0
40.5
50.0


In [9]:
Bank_customers=np.array([['bikesh','ram','harshini','aishwarya','shewtha'],[65,78,90,81,84],[71,82,79,92]])

In [12]:
for i in Bank_customers:
    print('i= ',i)

i=  ['bikesh', 'ram', 'harshini', 'aishwarya', 'shewtha']
i=  [65, 78, 90, 81, 84]
i=  [71, 82, 79, 92]


In [13]:
for ele in Bank_customers.flatten():
    print(ele)

['bikesh', 'ram', 'harshini', 'aishwarya', 'shewtha']
[65, 78, 90, 81, 84]
[71, 82, 79, 92]


In [14]:
arr=np.array([10,20,30,40,50])
print("Elements:")
for ele in arr:
    print(ele)

Elements:
10
20
30
40
50


In [15]:
arr=np.array([[10,20,30],[40,50,60]])
print("Elements:")
for row in arr:
    print(row)

Elements:
[10 20 30]
[40 50 60]


In [16]:
arr=np.array([[10,20,30],[40,50,60]])
print("Elements:")
for row in arr:
    for ele in row:
        print(ele)

Elements:
10
20
30
40
50
60


In [17]:
arr=np.array([[10,20,30],[40,50,60]])
print("Elements:")
for row in arr:
    for ele in row:
        print(ele)
    print()    

Elements:
10
20
30

40
50
60

